name: custom_error_text_form_field
description: A TextFormField widget that lets you show the error message as an overlay.
version: 0.0.1
homepage: https://github.com/KevinVan720/custom_error_text_form_field

environment:
  sdk: "^3.5.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
